### ISSUE TITLE
Any tutorial to use this package

### ISSUE THREAD

**Issue by ghost** [cschu/ktoolu#2]
Are there any tutorial or examples to use this package? e.g., which command should be used under which conditions? what is the input and output? Thank you.

**Comment by ghost** [comment]
Oh, got it. can use python functionname --help

**Comment by cschu** [comment]
Hi camel315,

Sorry for the lack of documentation. ktoolu consists of three different modules/scripts.
kt_extract allows you to extract the reads that belong to a subtree of the taxonomic tree (e.g. if you just want members of a specific clade or other taxonomic group). Output is a set of reads that matches your taxonomic filter criteria.
kt_combine allows you to do set operations on classifications from two kraken-databases (e.g. in plant-pathogen analysis, you might want to check against a plant-db and, say, a bacterial db). kt_combine then outputs sets of reads that are only in set1, only in set2, in both sets, and unclassified.
Finally, kt_summarize generates you a krona-plot if you have krona-tools installed.

**Comment by ghost** [comment]
Thank you. Will it be possible to input multiple kraken outputs (like merged community) and then generate a krona map for the dataset?
